SITE_TITLE: 'Fabian Bao'
SITE_DESCRIPTION: 'Trade code for BEER ! üç∫'
SITE_URL: 'https://fabian4.site'
USER_NAME: 'Fabian Bao'
GITHUB_USERNAME: 'fabian4'
GOOGLE_ANALYTICS_ID: 'G-Y1J4J668V2'
SOCIAL_LINKS:
  - href: 'https://github.com/fabian4'
    title: 'GitHub'
    icon: 'fa-brands fa-github'
  - href: 'https://linkedin.com/in/fabian4'
    title: 'LinkedIn'
    icon: 'fa-brands fa-linkedin'
  - href: 'https://twitter.com/fabian_bao'
    title: 'Twitter'
    icon: 'fa-brands fa-x-twitter'
  - href: 'https://www.instagram.com/fabian.v.bao'
    title: 'Instagram'
    icon: 'fa-brands fa-instagram'
  - href: 'https://t.me/fabianbao'
    title: 'Telegram'
    icon: 'fa-brands fa-telegram-plane'
  - href: 'https://fabian4.site/rss.xml'
    title: 'RSS'
    icon: 'fa-solid fa-square-rss'
  - href: 'mailto:fabian.v.bao@gmail.com'
    title: 'Email'
    icon: 'fa-solid fa-envelope'